### ISSUE TITLE
Improvement: Cut audio smarter as OpenAI suggested

### ISSUE THREAD

**Issue by Chapoly1305** [ultmaster/whisper-movie#3]
As OpenAI pointed out, there is a size limit of 25MB and split is required. 
But cutting base on time may have the risk of breaking up sentences. 
OpenAI suggested a method as follows, 

```
from pydub import AudioSegment

song = AudioSegment.from_mp3("good_morning.mp3")

# PyDub handles time in milliseconds
ten_minutes = 10 * 60 * 1000

first_10_minutes = song[:ten_minutes]

first_10_minutes.export("good_morning_10.mp3", format="mp3")
```

You may consider refactor related functions reference to https://platform.openai.com/docs/guides/speech-to-text/longer-inputs

**Comment by Chapoly1305** [comment]
with using pydub, there will be an issue of unknowing when the clip starts and ends, so the results cannot be used for subtittles.

**Comment by ultmaster** [comment]
I think a reasonable approach is to use a vocal detector and cuts the audio when there is a silence that's long enough. This can also solve the problem that whisper tends to hallucinate sentences on silence (and moreover, saves costs).

But it's too complicated to implement and I'm having trouble finding a detector that's fast yet good enough. Therefore it's postponed.
